// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantBackend.Data;

#nullable disable

namespace Restaurant_backend.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251122141935_AddRestaurantTables")]
    partial class AddRestaurantTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8");

            modelBuilder.Entity("RestaurantBackend.Models.Entity.BanAn", b =>
                {
                    b.Property<int>("ban_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ma_qr")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("TEXT");

                    b.Property<string>("so_ban")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ban_id");

                    b.ToTable("BanAn");
                });

            modelBuilder.Entity("RestaurantBackend.Models.Entity.ChiTietDonHang", b =>
                {
                    b.Property<int>("chi_tiet_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("don_gia")
                        .HasColumnType("TEXT");

                    b.Property<int>("don_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("mon_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("so_luong")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("thanh_tien")
                        .HasColumnType("TEXT");

                    b.HasKey("chi_tiet_id");

                    b.HasIndex("don_id");

                    b.HasIndex("mon_id");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("RestaurantBackend.Models.Entity.DanhMuc", b =>
                {
                    b.Property<int>("danh_muc_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("mo_ta")
                        .HasColumnType("TEXT");

                    b.Property<string>("ten_danh_muc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("thu_tu_hien_thi")
                        .HasColumnType("INTEGER");

                    b.HasKey("danh_muc_id");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("RestaurantBackend.Models.Entity.DonHang", b =>
                {
                    b.Property<int>("don_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ban_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ghi_chu_khach")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ngay_cap_nhat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("TEXT");

                    b.Property<string>("so_don")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("tong_tien")
                        .HasColumnType("TEXT");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("don_id");

                    b.HasIndex("ban_id");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("RestaurantBackend.Models.Entity.MonAn", b =>
                {
                    b.Property<int>("mon_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("anh_url")
                        .HasColumnType("TEXT");

                    b.Property<bool>("co_san")
                        .HasColumnType("INTEGER");

                    b.Property<int>("danh_muc_id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("gia")
                        .HasColumnType("TEXT");

                    b.Property<string>("mo_ta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("TEXT");

                    b.Property<string>("ten_mon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("mon_id");

                    b.HasIndex("danh_muc_id");

                    b.ToTable("MonAn");
                });

            modelBuilder.Entity("RestaurantBackend.Models.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RestaurantBackend.Models.Entity.ChiTietDonHang", b =>
                {
                    b.HasOne("RestaurantBackend.Models.Entity.DonHang", "DonHang")
                        .WithMany("ChiTietDonHang")
                        .HasForeignKey("don_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantBackend.Models.Entity.MonAn", "MonAn")
                        .WithMany("ChiTietDonHang")
                        .HasForeignKey("mon_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("RestaurantBackend.Models.Entity.DonHang", b =>
                {
                    b.HasOne("RestaurantBackend.Models.Entity.BanAn", "BanAn")
                        .WithMany("DonHang")
                        .HasForeignKey("ban_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BanAn");
                });

            modelBuilder.Entity("RestaurantBackend.Models.Entity.MonAn", b =>
                {
                    b.HasOne("RestaurantBackend.Models.Entity.DanhMuc", "DanhMuc")
                        .WithMany("MonAn")
                        .HasForeignKey("danh_muc_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("RestaurantBackend.Models.Entity.BanAn", b =>
                {
                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("RestaurantBackend.Models.Entity.DanhMuc", b =>
                {
                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("RestaurantBackend.Models.Entity.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHang");
                });

            modelBuilder.Entity("RestaurantBackend.Models.Entity.MonAn", b =>
                {
                    b.Navigation("ChiTietDonHang");
                });
#pragma warning restore 612, 618
        }
    }
}
